version: "3.3"
services:
    api:
        image: variantyx_api_img
        container_name: variantyx_api_inst
        build:
            context: ./api
        ports:
            - '2022:2022'
        environment: 
            - NODE_ENV=docker
            - NODE_OPTIONS="--max-old-space-size=4096"
        volumes:
            - variantyxapidata:/usr/src/app
        links:
            - 'db:maria'
        networks:
            - variantyxfront
            - variantyxback
    app:
        image: variantyx_app_img
        container_name: variantyx_app_inst
        build:
            context: ./app
        ports:
            - '2023:2023'
        environment:
            - NODE_ENV=docker
            - NODE_OPTIONS="--max-old-space-size=4096"
        volumes:
            - variantyxappdata:/usr/src/app
        networks:
            - variantyxfront
    db:
        image: mariadb
        container_name: variantyx_db_inst
        environment:
            - MYSQL_DATABASE=objectdb
            - MYSQL_ROOT_PASSWORD=rootdb
        volumes:
            - ./db:/etc/mysql/conf.d:ro
            - ./db:/docker-entrypoint-initdb.d:ro
            - variantyxdbdata:/var/lib/mysql
        ports:
            - '2021:2021'
        networks:
            - variantyxback
networks:
    variantyxfront:
        driver: bridge
    variantyxback:
        driver: bridge
volumes:
    variantyxapidata:
    variantyxappdata:
    variantyxdbdata: